second_ecom/shop2/cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns=[
    path('add/<int:pro_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detial,name='cart_detials'),
    path('remove/<int:pro_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:pro_id>/', views.delete, name='delete')

]

second_ecom/shop2/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.AllProCat,name='AllProCat'),
    path('<slug:c_slug>/',views.AllProCat,name='Prod_by_cat'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProDet, name='ProDet')

]

second_ecom/shop2/search/urls.py
from django.urls import path
from .import views

app_name = 'search'

urlpatterns=[
    path('',views.search_result,name='search_result'),
    ]

second_ecom/shop2/shop2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

second_ecom/shop2/cart/models.py
from django.db import models
from home.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=200,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def Sub_Total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

second_ecom/shop2/home/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering=('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('home:Prod_by_cat',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def get_url(self):
        return reverse('home:ProDet',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.name

second_ecom/shop2/search/models.py
from django.db import models

# Create your models here.

second_ecom/shop2/cart/views.py
from django.shortcuts import render, redirect
from home.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render,get_object_or_404


# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,pro_id):
    product=Product.objects.get(id=pro_id)
    try:
        cart=Cart.objects.get(cart_id= _cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id= _cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detials')

def cart_detial(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)

            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,pro_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=pro_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detials')

def delete(request,pro_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=pro_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detials')

second_ecom/shop2/home/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def AllProCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(Paginator.num_pages)

    return render(request,'home.html',{'category':c_page,'products':products})


def ProDet(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

second_ecom/shop2/search/views.py
from django.shortcuts import render
from home.models import Product
from django.db.models import Q
# Create your views here.
def search_result(request):
    product=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        product=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':product})

second_ecom/shop2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block meta %} {% endblock %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/costom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>



    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">

    {% include 'header.html' %}
{% include 'navbar.html' %}
{% block body %}
{% endblock %}
    </div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

second_ecom/shop2/templates/cart.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
        this is our shopping bag page you can see your products in your bag and buy
    {% endblock %}
{% block title %}
cart
{% endblock %}
{% block body %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Food Bag Is Empty</h1>
        <br>
        <p class="text-center">Please click Here To <a href="{% url 'home:AllProCat' %}">Click Here</a> To Buy Some</p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Bag</h1>
        <br>
    </div>
</div>
{% endif %}
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_costom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td><a href="item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" height="100px" width="100px"></a></td>
                <td class="text-left">
                    {{cart_item.product.name}}
                <br>
                SKU: {{cart_item.product.id}}
                <br>
                price: $ {{cart_item.product.price}}
                <br>
                Qty: {{cart_item.quantity}} x $ {{cart_item.product.price}}
                </td>
                <td>
                    ${{cart_item.sub_total}}
                </td>
                {% if cart_items.quantity < cart_items.product.stcok %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>

                </td>
                {% else %}
                 <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>

                </td>
                {% endif %}


            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>checkout </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Please Review your Shopping Bag Items </td>
        </tr>
        <tr>
            <td class="text-left">Your Total Is:<strong>{{total}}</strong></td>
        </tr>
        </tbody>

    </table>
    <div class="mx-auto">
        <a href="{% url 'home:AllProCat'%}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        <a class="btn btn-danger btn-block my_custom_button" href="{% url 'home:AllProCat' %}">Make Payement</a>

    </div>
</div>
</div>



{% endblock %}

second_ecom/shop2/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; Abc restaurent pvt ltd All rights Recieved</p>
</div>

second_ecom/shop2/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'home:AllProCat' %}"> <img src="{% static 'img/iconr.png' %}" alt="image"    style="border-radius: 50%; width:130px; height:130px;"></a>
  </center>
</header>

second_ecom/shop2/templates/home.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    {% if category %}
        {{ category.description|truncatewords:120 }}
    {% else %}
    welcome to ABC restaurent we provide for your taste
    {% endif%}
    {% endblock %}
{% block title %}
{% if category %}
    {{ category.name }}----ABC Restaurent
    {% else %}
    see our veriety of dishes---ABC Restaurent
    {% endif %}
{% endblock %}
{% block body %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a  href="{% url 'home:AllProCat' %}">Our Product Collection</a></p>
    </div>
        </div>
</div>
{% endif %}
    <div class="mx-auto">
        {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
<br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
{% else %}
    <div>
    <img class="my_image my_image_padding" src="{% static 'img/abcbanner.png' %}" alt="{{category.name}}" width="1100px" height="450">
     </div>
<br>
<div>
    <h1 class="text-center my_title">Our Product Collections </h1>
    <p class="text-justify">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
</div>
{% endif %}
<div class="container ">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <h6>{{product.price}}</h6>
                </div>
            </div>
            </div>

        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

second_ecom/shop2/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'home:AllProCat' %}">Buy</a>
        </li>
        <li class="nav-item dropdown {% if 'home' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  shop by Category
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'home:AllProCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detials' %}"><i class="fa fa-shopping-bag"></i></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" method="GET" action="{% url 'search:search_result' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

second_ecom/shop2/templates/product.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
        {{ product.description|truncatewords:120 }}
    {% endblock %}
{% block title %}
{% if product %}
    {{ product.name }}----ABC Restaurent
    {% endif %}
{% endblock %}
{% block body %}
<div class="row my_product_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'home:AllProCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a></p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" height="320px" width="300px">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p><b>${{product.price}}</b></p>
            <p class="my_title"> Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_product_text"><b>Out Of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
            {% endif %}
        </div>
    </div>
    </div>
</div>
{% endblock %}

second_ecom/shop2/templates/search.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    welcome to ABC restaurent we provide for your taste
  {% endblock %}
{% block title %}
    Search
{% endblock %}
{% block body %}
<div>
    <p class="text-center my_search_text">you Have Searched For:<b>"{{query}}"</b></p>

</div>
<div class="container ">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="card" style="width: 18rem;">
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <h6>{{product.price}}</h6>
                    <a class="btn btn-primary">Add To Bag</a>
                </div>
             </div>
            </div>
        </div>
        {% empty %}
        <div class="mx-auto">
            <p class="text-center my_search_text">0 Results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}